### ISSUE TITLE
Failure to create staffroll.txt

### ISSUE THREAD

**Issue by WhitetailAni** [RoadrunnerWMC/nsmbw-staffroll-tool#2]
Reencoding works fine, but when attempting to decode staffroll.bin it spits out
`J:\roll>py staffroll.py J:\roll\staffroll.bin J:\roll\staffroll.txt
Traceback (most recent call last):
  File "J:\roll\staffroll.py", line 102, in <module>
    main()
  File "J:\roll\staffroll.py", line 84, in main
    lines = staffroll_lib.readStaffrollBin(data)
  File "J:\roll\staffroll_lib.py", line 423, in readStaffrollBin
    lines.append(StaffrollLine.fromBinFile(f))
  File "J:\roll\staffroll_lib.py", line 109, in fromBinFile
    new_contents = Contents(char_data & 0xF)
  File "H:\Users\David\AppData\Local\Programs\Python\Python39\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "H:\Users\David\AppData\Local\Programs\Python\Python39\lib\enum.py", line 702, in __new__
    raise ve_exc
ValueError: 15 is not a valid Contents`
This is an edited file that causes the game to crash when loading the credits, so that could be it. I would like to decode it to edit and fix since I was stupid and didn't make backups.

**Comment by RoadrunnerWMC** [comment]
Huh... I get the feeling it's getting misaligned and trying to read the data for a blank line as part of a non-blank line. Anyway, da72901 should make it at least not crash in that way. If it still doesn't work, though, could you send the bin file here?

**Comment by WhitetailAni** [comment]
Still no luck. Error:
`J:\roll>py staffroll.py J:\roll\staffroll.bin J:\roll\staffroll.txt
Traceback (most recent call last):
  File "J:\roll\staffroll.py", line 102, in <module>
    main()
  File "J:\roll\staffroll.py", line 84, in main
    lines = staffroll_lib.readStaffrollBin(data)
  File "J:\roll\staffroll_lib.py", line 423, in readStaffrollBin
    lines.append(StaffrollLine.fromBinFile(f))
  File "J:\roll\staffroll_lib.py", line 102, in fromBinFile
    char_data, = struct.unpack_from('>I', f.read(4))
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)`
And .bin file:
[https://drive.google.com/file/d/1q9ZDPTK7eryd4nL-fcxpRU_NC36a7Put/view?usp=sharing](url)

**Comment by WhitetailAni** [comment]
It seems that it was an issue with my staffroll.bin file since taking the stock staffroll.bin file worked.
Re-editing the stock staffroll.bin with my edits and closing.

**Comment by RoadrunnerWMC** [comment]
Sorry for the delay. The fix for your previous issue, in fd6cc21, turned out to be wrong, resulting in the tool creating invalid bin files. I've fixed it properly now in 1fd21d8.

**Comment by WhitetailAni** [comment]
Yep, that fixed it. Thanks!
